import fs from 'fs';

// This is a minimal valid 192x192 transparent PNG (base64)
const png192 = "iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAQAAAAYjO38AAAAaUlEQVR42u3BAQ0AAADCIPunNtx3cABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgdwXQAAABhJzHAAAAAElFTkSuQmCC";
fs.writeFileSync('public/pwa-192x192.png', Buffer.from(png192, 'base64'));

// This is a minimal valid 512x512 transparent PNG (base64)
const png512 = "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAQAAAD0eNTmAABAAElEQVR42u3BAQ0AAADCIPunNtx3cABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgdwXQAAABhJzHAAAAAElFTkSuQmCC";
fs.writeFileSync('public/pwa-512x512.png', Buffer.from(png512, 'base64'));

// Make a colored icon with basic shapes using canvas to be safe
